(()=>{
'use strict';
const AI_FN='https://vnnvuxccazkdzwqjmntz.supabase.co/functions/v1/delivery-note-ai';
const UPLOAD_FN='https://vnnvuxccazkdzwqjmntz.supabase.co/functions/v1/delivery-upload-url';
const CHUNK_PAGES=1,MAX_CONCURRENCY=2;
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const keyFor=s=>{let h=2166136261;for(let i=0;i<s.length;i++){h^=s.charCodeAt(i);h=Math.imul(h,16777619)}return(h>>>0).toString(36)};
const mmss=n=>{n=Math.max(0,Math.round(n));const m=Math.floor(n/60),s=n%60;return m?`${m}分${String(s).padStart(2,'0')}秒`:`${s}秒`};
async function post(url,body){const r=await fetch(url,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});let j={};try{j=await r.json()}catch{}if(!r.ok)throw new Error(j.error||`HTTP ${r.status}`);return j}
async function directUpload(blob,fileName){const mime=blob.type||'application/pdf';const sig=await post(UPLOAD_FN,{file_name:fileName,mime_type:mime,size:blob.size});const {error}=await supabaseClient.storage.from('delivery-notes').uploadToSignedUrl(sig.path,sig.token,blob,{contentType:mime,upsert:false});if(error)throw new Error('Storage保存に失敗しました: '+error.message);return sig.path}
async function ensurePdfLib(){if(window.PDFLib)return;await new Promise((res,rej)=>{const x=document.createElement('script');x.src='https://cdn.jsdelivr.net/npm/pdf-lib@1.17.1/dist/pdf-lib.min.js';x.onload=res;x.onerror=()=>rej(new Error('PDF分割ライブラリを読み込めませんでした'));document.head.appendChild(x)})}
async function splitFile(file){if(file.type!=='application/pdf'&&!file.name.toLowerCase().endsWith('.pdf'))return[{blob:file,label:'画像',pageNo:1}];await ensurePdfLib();const src=await file.arrayBuffer(),doc=await PDFLib.PDFDocument.load(src),n=doc.getPageCount(),out=[];for(let st=0;st<n;st+=CHUNK_PAGES){const ed=Math.min(st+CHUNK_PAGES,n),part=await PDFLib.PDFDocument.create(),idx=[];for(let i=st;i<ed;i++)idx.push(i);const copied=await part.copyPages(doc,idx);copied.forEach(p=>part.addPage(p));const bytes=await part.save();out.push({blob:new Blob([bytes],{type:'application/pdf'}),label:`${st+1}ページ`,pageNo:st+1})}return out}
function init(){
 const tabs=document.querySelector('.material-tabs'),app=document.getElementById('materialApp');if(!tabs||!app)return;
 document.getElementById('mp-delivery')?.remove();
 const old=tabs.querySelector('.material-tab[data-tab="delivery"]');
 const st=document.createElement('style');st.textContent=`.delivery-step{background:#f7f9fc;border:1px solid #d8dee8;border-radius:14px;padding:14px;margin:10px 0}.delivery-pick{display:inline-block;margin-top:12px;padding:13px 18px;border-radius:12px;background:#2563eb;color:#fff;font-weight:800;cursor:pointer}.delivery-hidden{position:absolute;left:-9999px}.delivery-note{font-size:12px;line-height:1.65;color:#64748b}.delivery-live{background:#eff6ff;border:2px solid #60a5fa;border-radius:14px;padding:14px;margin-top:10px;color:#1e3a8a;font-weight:800}.delivery-live .big{font-size:20px;margin-bottom:6px}.delivery-live .eta{font-size:18px;margin-top:5px}.delivery-result,.delivery-progress{background:#fff;border:1px solid #d8dee8;border-radius:14px;padding:14px;margin-top:10px}.delivery-progress.ok{background:#f0fdf4;border-color:#86efac}.delivery-progress.bad{background:#fff7ed;border-color:#fdba74}.delivery-grid{display:grid;grid-template-columns:1fr 1fr;gap:8px}.delivery-grid label{font-size:11px;color:#64748b}.delivery-grid input{width:100%;box-sizing:border-box;padding:10px;border:1px solid #cbd5e1;border-radius:9px;font-size:14px}.delivery-wide{grid-column:1/-1}.delivery-confirm,.delivery-bulk button,.retry-btn{width:100%;border:0;border-radius:10px;padding:12px;background:#15803d;color:#fff;font-weight:900;margin-top:10px}.retry-btn{background:#b45309}.delivery-done{background:#dcfce7!important;border-color:#86efac!important}.delivery-failed{background:#fff7ed!important;border-color:#f59e0b!important}.delivery-success{position:sticky;top:8px;z-index:5;background:#dcfce7;border:2px solid #22c55e;border-radius:12px;padding:12px;margin:10px 0;color:#14532d;font-weight:900}.delivery-warnings{background:#fff7ed;border:1px solid #f59e0b;color:#9a3412;border-radius:10px;padding:10px 12px;margin:8px 0;font-size:13px}.delivery-bulk{background:#ecfdf5;border:1px solid #86efac;border-radius:12px;padding:12px;margin:12px 0;color:#14532d}.delivery-source-btn{border:1px solid #2563eb;background:#eff6ff;color:#1d4ed8;border-radius:9px;padding:8px 11px;font-weight:800}.uncertain{border-color:#f59e0b!important;background:#fffbeb!important}@media(max-width:500px){.delivery-grid{grid-template-columns:1fr}}`;document.head.appendChild(st);
 const tab=old||document.createElement('button');if(!old){tab.className='material-tab';tab.dataset.tab='delivery';tab.textContent='納品書取込';tabs.insertBefore(tab,tabs.children[1]||null)}
 const s=document.createElement('section');s.className='material-panel';s.id='mp-delivery';s.style.display='none';s.innerHTML=`<div class="card"><div class="card-title">納品書を取り込む</div><div id="deliverySuccess"></div><div class="delivery-step"><b>① PDF・画像を選ぶ</b><br><label class="delivery-pick" for="deliveryFiles">PDF・画像を選ぶ</label><input id="deliveryFiles" class="delivery-hidden" type="file" accept="application/pdf,image/*" multiple><div id="deliveryFilesView" class="delivery-note">まだ選択されていません</div></div><div class="delivery-step"><b>② AIで読み取る</b><br>大量PDFは1ページずつ処理します。途中で1ページ失敗しても他のページは続行します。<br><button class="btn btn-primary" id="deliveryStart">AIで読み取る</button><div id="deliveryStatus" class="delivery-note" style="margin-top:10px"></div><div id="deliveryLive"></div></div><div id="deliveryBulk"></div><div id="deliveryProgress"></div><div id="deliveryResults"></div></div>`;app.appendChild(s);
 const show=()=>{document.querySelectorAll('.material-tab').forEach(x=>x.classList.remove('active'));document.querySelectorAll('.material-panel').forEach(x=>{x.classList.remove('active');x.style.display='none'});tab.classList.add('active');s.classList.add('active');s.style.display='block'};tab.onclick=e=>{e.preventDefault();e.stopPropagation();show()};
 const f=s.querySelector('#deliveryFiles'),v=s.querySelector('#deliveryFilesView'),status=s.querySelector('#deliveryStatus'),live=s.querySelector('#deliveryLive'),results=s.querySelector('#deliveryResults'),success=s.querySelector('#deliverySuccess'),bulk=s.querySelector('#deliveryBulk'),progress=s.querySelector('#deliveryProgress');let cards=[];
 function card(row,idx,requestKey){const c=document.createElement('div'),warns=Array.isArray(row.warnings)?row.warnings:[];c.className='delivery-result'+(row.uncertain?' uncertain':'');c.dataset.safe=(!row.uncertain&&!warns.length)?'1':'0';const wh=warns.length?`<div class="delivery-warnings"><b>⚠ 登録前に確認</b><br>${warns.map(w=>'・'+esc(w)).join('<br>')}</div>`:'';c.innerHTML=`<div style="font-weight:900">${esc(row.source_file_name||row.file_name||'納品書')} / ${row.page_number?esc(row.page_number)+'ページ / ':''}明細 ${idx+1}</div>${wh}<div><button type="button" class="delivery-source-btn">元の納品書を見る</button></div><div class="delivery-grid">${[['delivery_date','納品日'],['supplier','サプライヤー'],['manufacturer','材料メーカー'],['name','品名'],['category','分類'],['spec','規格・材質'],['thickness_mm','厚み mm'],['purchase_form','サイズ・購入形態'],['quantity','数量'],['unit','単位'],['unit_price','単価'],['amount','金額'],['notes','備考']].map(([k,l])=>`<div class="${k==='notes'?'delivery-wide':''}"><label>${l}</label><input data-k="${k}" value="${esc(row[k]??'')}"></div>`).join('')}</div><button class="delivery-confirm">材料・単価・在庫を登録</button><div class="delivery-note msg"></div>`;c.querySelector('.delivery-source-btn').onclick=async()=>{try{const j=await post(AI_FN,{action:'source_url',path:row.source_file_path});window.open(j.url,'_blank','noopener')}catch(e){alert('原本を開けませんでした：'+e.message)}};const btn=c.querySelector('.delivery-confirm'),msg=c.querySelector('.msg');c._confirm=async()=>{if(c.classList.contains('delivery-done'))return true;const r={file_name:row.file_name,source_file_path:row.source_file_path||'',source_file_name:row.source_file_name||row.file_name||''};c.querySelectorAll('[data-k]').forEach(el=>{const k=el.dataset.k;r[k]=['thickness_mm','quantity','unit_price','amount'].includes(k)?(el.value===''?null:Number(el.value)):el.value});btn.disabled=true;btn.textContent='登録中…';try{const j=await post(AI_FN,{action:'confirm',request_key:requestKey,row:r});c.classList.add('delivery-done');btn.textContent='✓ 登録済み';msg.textContent=`在庫へ${j.stock_added||0}${r.unit||''}入庫しました。`;return true}catch(e){c.classList.add('delivery-failed');btn.disabled=false;btn.textContent='再登録する';msg.textContent='登録エラー：'+e.message;return false}};btn.onclick=async()=>{await c._confirm();rebuildBulk()};cards.push(c);return c}
 function rebuildBulk(){const safe=cards.filter(c=>c.dataset.safe==='1'&&!c.classList.contains('delivery-done'));const bad=cards.filter(c=>c.dataset.safe!=='1'&&!c.classList.contains('delivery-done'));bulk.innerHTML='';if(safe.length){bulk.innerHTML=`<div class="delivery-bulk"><b>確認不要の明細：${safe.length}件</b><div class="delivery-note">警告のない明細だけ登録します。</div><button>安全な${safe.length}件を一括登録</button></div>`;bulk.querySelector('button').onclick=async()=>{const btn=bulk.querySelector('button'),targets=cards.filter(c=>c.dataset.safe==='1'&&!c.classList.contains('delivery-done'));btn.disabled=true;let ok=0,fail=0;for(let i=0;i<targets.length;i++){btn.textContent=`登録中 ${i+1}/${targets.length}…`;if(await targets[i]._confirm())ok++;else fail++}btn.disabled=false;btn.textContent=fail?`✓ ${ok}件成功 / ${fail}件失敗`:`✓ ${ok}件を一括登録しました`;success.innerHTML=`<div class="delivery-success">登録結果：✓ ${ok}件成功${fail?`　⚠ ${fail}件失敗`:''}</div>`}}if(bad.length){const d=document.createElement('div');d.className='delivery-warnings';d.innerHTML=`<b>⚠ 要確認の明細：${bad.length}件</b><br>この明細は自動登録しません。内容を確認して個別に登録してください。`;bulk.appendChild(d)}}
 f.onchange=()=>{const a=[...f.files];v.innerHTML=a.length?`<b>${a.length}ファイル選択</b><br>`+a.map((x,i)=>`${i+1}. ${esc(x.name)} (${(x.size/1024/1024).toFixed(1)}MB)`).join('<br>'):'まだ選択されていません';cards=[];results.innerHTML=success.innerHTML=bulk.innerHTML=progress.innerHTML=live.innerHTML='';status.textContent=''};
 s.querySelector('#deliveryStart').onclick=async()=>{const files=[...f.files];if(!files.length){alert('先にPDF・画像を選んでください');return}const start=s.querySelector('#deliveryStart');start.disabled=true;start.textContent='AI読み取り中…';cards=[];results.innerHTML=success.innerHTML=bulk.innerHTML=progress.innerHTML='';let allJobs=[],sourceMap=new Map();try{
   for(let fi=0;fi<files.length;fi++){const file=files[fi];status.textContent=`原本保存中 ${fi+1}/${files.length}：${file.name}`;const sourcePath=await directUpload(file,file.name);sourceMap.set(file,sourcePath);const chunks=await splitFile(file);chunks.forEach((chunk,ci)=>allJobs.push({file,chunk,ci,sourcePath}))}
 }catch(e){start.disabled=false;start.textContent='AIで読み取る';status.textContent='原本保存またはPDF分割に失敗しました：'+e.message;return}
 const total=allJobs.length;let finished=0,ok=0,fail=0,cursor=0;const durations=[];const begun=Date.now();
 const boxes=allJobs.map(j=>{const d=document.createElement('div');d.className='delivery-progress';d.innerHTML=`<b>${esc(j.file.name)}</b> ${esc(j.chunk.label)}：待機中`;progress.appendChild(d);return d});
 function paint(){const elapsed=(Date.now()-begun)/1000,remain=total-finished;let eta=null;if(finished>0){const avg=durations.reduce((a,b)=>a+b,0)/durations.length;eta=Math.ceil(remain*avg/MAX_CONCURRENCY)}const pct=total?Math.round(finished/total*100):0;live.innerHTML=`<div class="delivery-live"><div class="big">🤖 AI読み取り中　${finished}/${total}ページ（${pct}%）</div><div>成功 ${ok}ページ　／　失敗 ${fail}ページ　／　残り ${remain}ページ</div><div class="eta">${eta==null?'残り時間：計算中…':'残り時間：約 '+mmss(eta)}</div><div class="delivery-note">経過時間 ${mmss(elapsed)}　※残り時間は処理実績から随時補正します</div></div>`;status.textContent=`${finished}/${total}ページ処理済み`}
 paint();const clock=setInterval(paint,1000);
 async function worker(){while(true){const i=cursor++;if(i>=allJobs.length)return;const j=allJobs[i],box=boxes[i],t0=Date.now();box.innerHTML=`<b>${esc(j.file.name)}</b> ${esc(j.chunk.label)}：🤖 AI読み取り中…`;try{const chunkPath=await directUpload(j.chunk.blob,`${j.file.name}-page-${j.chunk.pageNo}.pdf`);const a=await post(AI_FN,{action:'analyze_storage',file_name:`${j.file.name} ${j.chunk.label}`,source_file_name:j.file.name,source_file_path:j.sourcePath,chunk_path:chunkPath,mime_type:'application/pdf'});const its=a.items||[];box.className='delivery-progress ok';box.innerHTML=`<b>${esc(j.file.name)}</b> ${esc(j.chunk.label)}：✓ ${its.length}明細`;its.forEach((x,k)=>results.appendChild(card({...x,file_name:j.file.name,page_number:j.chunk.pageNo},k,keyFor(`${j.sourcePath}|${j.chunk.pageNo}|${k}|${x.name}|${x.spec}|${x.unit_price}`))));ok++;}catch(e){box.className='delivery-progress bad';box.innerHTML=`<b>${esc(j.file.name)}</b> ${esc(j.chunk.label)}：⚠ ${esc(e.message)}`;fail++;}finally{durations.push((Date.now()-t0)/1000);if(durations.length>12)durations.shift();finished++;paint();rebuildBulk()}}}
 await Promise.all(Array.from({length:Math.min(MAX_CONCURRENCY,total)},()=>worker()));clearInterval(clock);paint();start.disabled=false;start.textContent='AIで読み取る';live.innerHTML=`<div class="delivery-live"><div class="big">✓ AI読み取り完了　${finished}/${total}ページ</div><div>成功 ${ok}ページ　／　失敗 ${fail}ページ</div><div class="delivery-note">総処理時間 ${mmss((Date.now()-begun)/1000)}</div></div>`;status.textContent=`AI読取完了：${cards.length}明細。内容を確認してください。`;rebuildBulk()};
}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
})();