(()=>{
const FN='https://vnnvuxccazkdzwqjmntz.supabase.co/functions/v1/delivery-note-ai';
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const fileToBase64=file=>new Promise((res,rej)=>{const r=new FileReader();r.onload=()=>res(String(r.result).split(',')[1]||'');r.onerror=rej;r.readAsDataURL(file)});
async function call(body){const r=await fetch(FN,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const j=await r.json();if(!r.ok)throw new Error(j.error||'処理に失敗しました');return j}
function init(){const tabs=document.querySelector('.material-tabs'),app=document.getElementById('materialApp');if(!tabs||!app||document.getElementById('mp-delivery'))return;
const st=document.createElement('style');st.textContent=`
@media(max-width:700px){.material-tabs{display:grid!important;grid-template-columns:1fr 1fr!important;gap:8px!important;overflow:visible!important}.material-tab{width:100%!important;min-width:0!important;padding:12px 8px!important;font-size:14px!important}.material-tab:last-child{grid-column:1/-1!important}}
.delivery-step{background:#f7f9fc;border:1px solid #d8dee8;border-radius:14px;padding:14px;margin:10px 0;color:#1f2937}.delivery-step b{display:block;margin-bottom:4px}.delivery-pick{display:inline-block;margin-top:12px;padding:13px 18px;border-radius:12px;background:#2563eb;color:white;font-weight:800;cursor:pointer}.delivery-hidden{position:absolute;left:-9999px}.delivery-file-list{margin-top:12px;font-size:13px;line-height:1.7}.delivery-note{font-size:12px;color:#64748b;line-height:1.6}.delivery-result{background:#fff;border:1px solid #d8dee8;border-radius:14px;padding:14px;margin-top:12px;color:#111827}.delivery-grid{display:grid;grid-template-columns:1fr 1fr;gap:8px}.delivery-grid label{font-size:11px;color:#64748b}.delivery-grid input{width:100%;box-sizing:border-box;padding:10px;border:1px solid #cbd5e1;border-radius:9px;font-size:14px;background:#fff;color:#111827}.delivery-wide{grid-column:1/-1}.delivery-actions{display:flex;gap:8px;margin-top:10px}.delivery-confirm{flex:1;border:0;border-radius:10px;padding:12px;background:#16a34a;color:white;font-weight:800}.delivery-done{background:#dcfce7!important;border-color:#86efac!important}.uncertain{border-color:#f59e0b!important;background:#fffbeb!important}@media(max-width:500px){.delivery-grid{grid-template-columns:1fr}}
`;document.head.appendChild(st);
const b=document.createElement('button');b.className='material-tab';b.dataset.tab='delivery';b.textContent='納品書取込';b.style.background='#2563eb';b.style.color='#fff';b.style.borderColor='#2563eb';tabs.insertBefore(b,tabs.children[1]||null);
const s=document.createElement('section');s.className='material-panel';s.id='mp-delivery';s.style.display='none';s.innerHTML=`<div class="card"><div class="card-title">納品書を取り込む</div><div class="delivery-step"><b>① DS-787Wでスキャン</b>納品書をPDFで保存します。</div><div class="delivery-step"><b>② PDFを選ぶ</b><label class="delivery-pick" for="deliveryFiles">PDF・画像を選ぶ</label><input id="deliveryFiles" class="delivery-hidden" type="file" accept="application/pdf,image/*" multiple><div id="deliveryFilesView" class="delivery-file-list">まだ選択されていません</div></div><div class="delivery-step"><b>③ AIで読み取る</b><button class="btn btn-primary" id="deliveryStart">AIで読み取る</button><div id="deliveryStatus" class="delivery-note" style="margin-top:10px"></div></div><div id="deliveryResults"></div></div>`;app.appendChild(s);
function showDelivery(){
 document.querySelectorAll('.material-tab').forEach(x=>x.classList.remove('active'));
 document.querySelectorAll('.material-panel').forEach(x=>{x.classList.remove('active');x.style.display='none'});
 b.classList.add('active');s.classList.add('active');s.style.display='block';
 setTimeout(()=>{const y=s.getBoundingClientRect().top+window.pageYOffset-8;window.scrollTo({top:y,behavior:'auto'})},30);
}
b.addEventListener('click',e=>{e.preventDefault();e.stopPropagation();showDelivery()});
[...tabs.querySelectorAll('.material-tab')].filter(x=>x!==b).forEach(x=>x.addEventListener('click',()=>{s.style.display='none';s.classList.remove('active')}));
const f=s.querySelector('#deliveryFiles'),v=s.querySelector('#deliveryFilesView'),status=s.querySelector('#deliveryStatus'),results=s.querySelector('#deliveryResults');
f.addEventListener('change',()=>{const a=[...f.files];v.innerHTML=a.length?`<b>${a.length}ファイル選択</b><br>`+a.map((x,i)=>`${i+1}. ${esc(x.name)}`).join('<br>'):'まだ選択されていません';results.innerHTML='';status.textContent='';});
function card(row,i){const c=document.createElement('div');c.className='delivery-result'+(row.uncertain?' uncertain':'');c.dataset.i=i;c.innerHTML=`<div style="font-weight:900;margin-bottom:8px">${esc(row.file_name||'納品書')} / 明細 ${i+1}${row.uncertain?' ⚠要確認':''}</div><div class="delivery-grid"><div><label>納品日</label><input data-k="delivery_date" value="${esc(row.delivery_date)}"></div><div><label>サプライヤー</label><input data-k="supplier" value="${esc(row.supplier)}"></div><div><label>材料メーカー</label><input data-k="manufacturer" value="${esc(row.manufacturer)}"></div><div><label>品名</label><input data-k="name" value="${esc(row.name)}"></div><div><label>分類</label><input data-k="category" value="${esc(row.category)}"></div><div><label>規格・材質</label><input data-k="spec" value="${esc(row.spec)}"></div><div><label>厚み mm</label><input data-k="thickness_mm" type="number" step="any" value="${row.thickness_mm??''}"></div><div><label>サイズ・購入形態</label><input data-k="purchase_form" value="${esc(row.purchase_form)}"></div><div><label>数量</label><input data-k="quantity" type="number" step="any" value="${row.quantity??''}"></div><div><label>単位</label><input data-k="unit" value="${esc(row.unit)}"></div><div><label>単価</label><input data-k="unit_price" type="number" step="any" value="${row.unit_price??''}"></div><div><label>金額</label><input data-k="amount" type="number" step="any" value="${row.amount??''}"></div><div class="delivery-wide"><label>備考</label><input data-k="notes" value="${esc(row.notes)}"></div></div><div class="delivery-actions"><button class="delivery-confirm">この内容で材料・単価を登録</button></div><div class="delivery-note msg" style="margin-top:8px"></div>`;
 c.querySelector('.delivery-confirm').onclick=async()=>{const btn=c.querySelector('.delivery-confirm'),msg=c.querySelector('.msg');const r={file_name:row.file_name};c.querySelectorAll('[data-k]').forEach(el=>{const k=el.dataset.k;r[k]=['thickness_mm','quantity','unit_price','amount'].includes(k)?(el.value===''?null:Number(el.value)):el.value});btn.disabled=true;btn.textContent='登録中…';try{await call({action:'confirm',row:r});c.classList.add('delivery-done');btn.textContent='登録済み';msg.textContent='材料マスターと単価履歴へ反映しました。';}catch(e){btn.disabled=false;btn.textContent='この内容で材料・単価を登録';msg.textContent='エラー：'+e.message;}};return c}
s.querySelector('#deliveryStart').addEventListener('click',async()=>{const files=[...f.files];if(!files.length){alert('先にPDF・画像を選んでください');return}results.innerHTML='';status.textContent=`0 / ${files.length} ファイル処理中…`;const rows=[];for(let fi=0;fi<files.length;fi++){const file=files[fi];try{const base64=await fileToBase64(file);const j=await call({action:'analyze',file_name:file.name,mime_type:file.type||'application/pdf',base64});(j.items||[]).forEach(x=>rows.push({...x,file_name:file.name}));status.textContent=`${fi+1} / ${files.length} ファイル読み取り済み`; }catch(e){const d=document.createElement('div');d.className='delivery-result uncertain';d.textContent=`${file.name}：エラー ${e.message}`;results.appendChild(d)}}rows.forEach((r,i)=>results.appendChild(card(r,i)));if(rows.length)status.textContent=`AI読取完了：${rows.length}明細。内容を確認して、緑の登録ボタンを押してください。`;});
}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
})();