(function(){
'use strict';
const yen=n=>'¥'+Number(n||0).toLocaleString('ja-JP',{maximumFractionDigits:0});
function wait(){if(!window.supabaseClient){setTimeout(wait,200);return;} boot();}
async function boot(){const {data:{user}}=await supabaseClient.auth.getUser();if(!user)return;const {data:profile}=await supabaseClient.from('app_users').select('role,display_name,active').eq('user_id',user.id).maybeSingle();window.companyProfile=profile||{role:'staff'};if(profile?.role!=='owner'||profile?.active===false)return;addOwnerHub();}
function addOwnerHub(){if(document.getElementById('management-hub-button'))return;const btn=document.createElement('button');btn.id='management-hub-button';btn.type='button';btn.textContent='経営';btn.style.cssText='position:fixed;right:16px;top:max(16px,env(safe-area-inset-top));z-index:9998;background:#111827;color:#fff;border:0;border-radius:999px;padding:10px 16px;font-weight:800;box-shadow:0 4px 16px #0003';btn.onclick=openHub;document.body.appendChild(btn);}
async function metrics(){const now=new Date(), y=now.getFullYear(), m=String(now.getMonth()+1).padStart(2,'0'), start=`${y}-${m}-01`, next=new Date(y,now.getMonth()+1,1).toISOString().slice(0,10);const [est,mat,pay,att]=await Promise.all([supabaseClient.from('estimates').select('amount,status').gte('estimate_date',start).lt('estimate_date',next),supabaseClient.from('materials').select('id,reorder_point').eq('active',true),supabaseClient.from('payroll_monthly').select('total_company_cost').eq('payroll_month',start),supabaseClient.from('attendance_records').select('regular_minutes,overtime_minutes').gte('work_date',start).lt('work_date',next).eq('confirmed',true)]);const e=est.data||[], p=pay.data||[], a=att.data||[];return{month:`${y}年${Number(m)}月`,estimateAmount:e.reduce((s,x)=>s+Number(x.amount||0),0),estimateCount:e.length,waiting:e.filter(x=>x.status==='回答待ち').reduce((s,x)=>s+Number(x.amount||0),0),labor:p.reduce((s,x)=>s+Number(x.total_company_cost||0),0),hours:a.reduce((s,x)=>s+Number(x.regular_minutes||0)+Number(x.overtime_minutes||0),0)/60,materials:(mat.data||[]).length};}
async function openHub(){let ov=document.getElementById('management-hub-overlay');if(ov){ov.style.display='block';loadMetrics();return;}ov=document.createElement('div');ov.id='management-hub-overlay';ov.style.cssText='position:fixed;inset:0;z-index:9999;background:#f5f7fa;overflow:auto;padding:calc(18px + env(safe-area-inset-top)) 16px 40px';const modules=[['見積','見積登録・検索・分析'],['材料・在庫','材料価格・入出庫・発注'],['原価','材料費・労務費・加工費'],['勤怠・給与','タイムカードから人件費へ'],['営業','顧客・訪問・案件'],['製造','作業時間・工程・実績'],['経営分析','売上・粗利・原価・人件費']];ov.innerHTML=`<div style="max-width:760px;margin:auto"><div style="display:flex;justify-content:space-between;align-items:center"><div><div style="font-size:12px;color:#64748b">OWNER ONLY</div><h1 style="margin:2px 0 4px">経営</h1><div id="mh-month" style="font-size:13px;color:#64748b"></div></div><button id="mh-close" style="border:0;background:#fff;border-radius:10px;padding:10px 14px">閉じる</button></div><div id="mh-metrics" style="display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:10px;margin:16px 0"><div style="background:#fff;border-radius:15px;padding:15px">集計中...</div></div><div style="font-size:13px;font-weight:800;color:#475569;margin:18px 0 8px">業務アプリ</div><div style="display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:10px">${modules.map(m=>`<div style="background:#fff;border:1px solid #e2e8f0;border-radius:15px;padding:16px"><div style="font-weight:800;font-size:16px">${m[0]}</div><div style="font-size:12px;color:#64748b;margin-top:6px;line-height:1.5">${m[1]}</div></div>`).join('')}</div></div>`;document.body.appendChild(ov);ov.querySelector('#mh-close').onclick=()=>ov.style.display='none';loadMetrics();}
async function loadMetrics(){const box=document.getElementById('mh-metrics');if(!box)return;try{const x=await metrics();document.getElementById('mh-month').textContent=x.month+' 現在';const cards=[['見積総額',yen(x.estimateAmount),`${x.estimateCount}件`],['回答待ち',yen(x.waiting),'見積ステータスから集計'],['会社負担人件費',yen(x.labor),'給与計算済み分'],['確認済み労働時間',x.hours.toLocaleString('ja-JP',{maximumFractionDigits:1})+'h','勤怠から集計'],['登録材料',x.materials+'種類','材料マスター']];box.innerHTML=cards.map(c=>`<div style="background:#fff;border:1px solid #e2e8f0;border-radius:15px;padding:15px"><div style="font-size:12px;color:#64748b">${c[0]}</div><div style="font-size:21px;font-weight:900;margin:5px 0">${c[1]}</div><div style="font-size:11px;color:#94a3b8">${c[2]}</div></div>`).join('');}catch(e){box.innerHTML='<div style="background:#fff;border-radius:15px;padding:15px">集計データを取得できませんでした。</div>';}}
wait();
})();