'use strict';
(function(){
  const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  let busy=false;
  function addStyles(){if(document.getElementById('miDeleteStyle'))return;const s=document.createElement('style');s.id='miDeleteStyle';s.textContent='.mi-delete-btn{margin-top:8px;border:1px solid #d7a6a1;background:#fff;color:#b42318;border-radius:8px;padding:6px 12px;font-size:12px;font-weight:800}.mi-delete-btn:disabled{opacity:.45}';document.head.appendChild(s)}
  async function activeMaterials(){if(!window.supabaseClient)return[];const {data,error}=await supabaseClient.from('materials').select('id,name,spec,purchase_form,supplier').eq('active',true).order('name');if(error){console.error('delete materials load',error);return[]}return data||[]}
  function rowText(m){return [m.name,m.spec,m.purchase_form,m.supplier].filter(Boolean).join(' / ')}
  async function attach(){if(busy||!document.getElementById('miList'))return;busy=true;try{addStyles();const mats=await activeMaterials();const rows=[...document.querySelectorAll('#miList .mi-item')];rows.forEach(row=>{if(row.querySelector('.mi-delete-btn'))return;const text=(row.textContent||'').replace(/\s+/g,' ');const m=mats.find(x=>text.includes(x.name)&&(!x.spec||text.includes(x.spec))&&(!x.purchase_form||text.includes(x.purchase_form)));if(!m)return;const left=row.firstElementChild;if(!left)return;const b=document.createElement('button');b.type='button';b.className='mi-delete-btn';b.textContent='削除';b.dataset.materialId=m.id;b.dataset.materialName=m.name;b.addEventListener('click',deleteMaterial);left.appendChild(b)})}finally{busy=false}}
  async function deleteMaterial(e){e.stopPropagation();const b=e.currentTarget,id=b.dataset.materialId,name=b.dataset.materialName;if(!confirm('「'+name+'」を削除しますか？\n\nテスト登録など、不要な材料だけ削除してください。'))return;b.disabled=true;b.textContent='確認中…';const {data:moves,error:me}=await supabaseClient.from('inventory_movements').select('id').eq('material_id',id).limit(1);if(me){console.error(me);alert('入出庫履歴の確認に失敗しました');b.disabled=false;b.textContent='削除';return}if(moves&&moves.length){alert('この材料には入出庫履歴があるため削除できません。\n本番データを誤って消さないための保護です。');b.disabled=false;b.textContent='削除';return}const {error:pe}=await supabaseClient.from('material_prices').delete().eq('material_id',id);if(pe){console.error(pe);alert('単価履歴の削除に失敗しました');b.disabled=false;b.textContent='削除';return}const {error}=await supabaseClient.from('materials').update({active:false}).eq('id',id);if(error){console.error(error);alert('材料の削除に失敗しました');b.disabled=false;b.textContent='削除';return}alert('「'+name+'」を削除しました');const tab=document.querySelector('.tab-btn[data-goto="materials"]');if(tab)tab.click();else location.reload()}
  function start(){if(!window.supabaseClient){setTimeout(start,150);return}setInterval(attach,800);document.addEventListener('click',e=>{if(e.target.closest('.tab-btn[data-goto="materials"],.mi-tab[data-mi="list"]'))setTimeout(attach,400)},true)}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',start);else start();
})();