(function(){
'use strict';
function wait(){if(!window.supabaseClient){setTimeout(wait,250);return;}boot();}
async function getAlerts(){const [{data:mats,error:e1},{data:moves,error:e2}]=await Promise.all([supabaseClient.from('materials').select('id,name,spec,stock_unit,reorder_point').eq('active',true),supabaseClient.from('inventory_movements').select('material_id,movement_type,quantity')]);if(e1||e2)return[];const bal={};(moves||[]).forEach(x=>{const q=Number(x.quantity||0);bal[x.material_id]=(bal[x.material_id]||0)+(x.movement_type==='in'?q:x.movement_type==='out'?-q:0);});return(mats||[]).filter(m=>m.reorder_point!==null&&m.reorder_point!==''&&Number(bal[m.id]||0)<=Number(m.reorder_point)).map(m=>({...m,stock:Number(bal[m.id]||0)}));}
async function boot(){setTimeout(render,700);document.addEventListener('click',e=>{if(e.target.closest('#miSaveMove'))setTimeout(render,1000);});}
async function render(){const alerts=await getAlerts();renderFactory(alerts);renderOwner(alerts);}
function renderFactory(alerts){if(new URLSearchParams(location.search).get('entry')!=='factory')return;const screen=document.getElementById('screen-materials');if(!screen)return;let box=document.getElementById('stock-alert-box');if(!box){box=document.createElement('div');box.id='stock-alert-box';screen.prepend(box);}if(!alerts.length){box.innerHTML='<div style="background:#ecfdf5;border:1px solid #a7f3d0;border-radius:14px;padding:13px;margin-bottom:12px;font-weight:800;color:#065f46">在庫不足アラートはありません</div>';return;}box.innerHTML=`<div style="background:#fff7ed;border:2px solid #fb923c;border-radius:14px;padding:13px;margin-bottom:12px"><div style="font-weight:900;font-size:17px;color:#9a3412">⚠ 発注してください　${alerts.length}件</div>${alerts.slice(0,8).map(a=>`<div style="padding-top:8px;margin-top:8px;border-top:1px solid #fed7aa;font-size:13px"><b>${esc(a.name)}</b>${a.spec?' '+esc(a.spec):''}<br>残り <b>${a.stock}</b> ${esc(a.stock_unit||'')} ／ 発注点 ${Number(a.reorder_point)}</div>`).join('')}</div>`;}
function renderOwner(alerts){const hub=document.getElementById('management-hub-overlay');if(!hub||hub.style.display==='none')return;let box=document.getElementById('owner-stock-alert');const metrics=document.getElementById('mh-metrics');if(!metrics)return;if(!box){box=document.createElement('div');box.id='owner-stock-alert';metrics.parentNode.insertBefore(box,metrics.nextSibling);}box.innerHTML=alerts.length?`<div style="background:#fff7ed;border:1px solid #fb923c;border-radius:14px;padding:13px;margin:0 0 14px"><b>⚠ 在庫不足 ${alerts.length}件</b><div style="font-size:12px;color:#9a3412;margin-top:5px">${alerts.slice(0,5).map(a=>esc(a.name)+' 残'+a.stock+esc(a.stock_unit||'')).join(' ／ ')}</div></div>`:'';}
function esc(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));}
window.refreshStockAlerts=render;wait();
})();